### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by GewelsJI** [4uiiurz1/keras-arcface#2]
```python
Traceback (most recent call last):
  File "train_liveness.py", line 142, in <module>
    epochs=EPOCHS)
  File "C:\Users\Gepeng-Ji\Anaconda3\envs\keras\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Gepeng-Ji\Anaconda3\envs\keras\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\Gepeng-Ji\Anaconda3\envs\keras\lib\site-packages\keras\engine\training_generator.py", line 144, in fit_generator
    val_x, val_y, val_sample_weight)
  File "C:\Users\Gepeng-Ji\Anaconda3\envs\keras\lib\site-packages\keras\engine\training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "C:\Users\Gepeng-Ji\Anaconda3\envs\keras\lib\site-packages\keras\engine\training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_2 to have 2 dimensions, but got array with shape (78, 2, 2)
```

**Comment by GewelsJI** [comment]
I think i have wrong programming in those lines, but i still have no idea to deal with it!
please help me, thx!
@4uiiurz1 
```python
# partition the data into training and testing splits using 75% of
# the data for training and the remaining 25% for testing
(trainX, testX, trainY, testY) = train_test_split(data, labels,
                                                  test_size=0.25, random_state=42)
trainY = to_categorical(trainY, 2)
testY = to_categorical(testY, 2)
```

**Comment by 4uiiurz1** [comment]
Hi!
Please paste your train_liveness.py here.

**Comment by 4uiiurz1** [comment]
Did you pass the tuple (X_train, y_train) to the generator? That is not right.
You must pass the tuple ([X_train, y_train], y_train) to the generator.

**Comment by GewelsJI** [comment]
Thanks to your generous help and this is my own `train_liveness.py` copys:

```python# USAGE
# python train_liveness.py --dataset dataset --model liveness.model --le le.pickle

# set the matplotlib backend so figures can be saved in the background
import matplotlib
matplotlib.use("Agg")

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from keras.preprocessing.image import ImageDataGenerator
from keras.utils.vis_utils import plot_model
from keras.models import Sequential, Model
from keras.layers.normalization import BatchNormalization
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.layers.core import Activation, Flatten, Dropout, Dense
from arcface.metrics import ArcFace
from keras.layers import Input
from keras import backend as K
from keras.optimizers import Adam
from keras.utils import to_categorical
from keras.utils import np_utils
from imutils import paths
import matplotlib.pyplot as plt
import numpy as np
import argparse
import pickle
import cv2
import os

# visible GPU devices
os.environ["CUDA_VISIBLE_DEVICES"]="0,1"

# construct the argument parser and parse the arguments
ap = argparse.ArgumentParser()
ap.add_argument("-d", "--dataset", required=True,
                help="path to input dataset")
ap.add_argument("-m", "--model", type=str, required=True,
                help="path to trained model")
ap.add_argument("-l", "--le", type=str, required=True,
                help="path to label encoder")
ap.add_argument("-p", "--plot", type=str, default="plot.png",
                help="path to output loss/accuracy plot")
args = vars(ap.parse_args())

# initialize the initial learning rate, batch size, and number of
# epochs to train for
INIT_LR = 1e-4
BS = 8
EPOCHS = 50
# set image parameter
height = 64
width = 64
depth = 3
classes = 2

# grab the list of images in our dataset directory, then initialize
# the list of data (i.e., images) and class images
print("[INFO] loading images...")
imagePaths = list(paths.list_images(args["dataset"]))
data = []
labels = []

for imagePath in imagePaths:
    # extract the class label from the filename, load the image and
    # resize it to be a fixed 32x32 pixels, ignoring aspect ratio
    label = imagePath.split(os.path.sep)[-2]
    image = cv2.imread(imagePath)
    image = cv2.resize(image, (height, width))

    # update the data and labels lists, respectively
    data.append(image)
    labels.append(label)

# convert the data into a NumPy array, then preprocess it by scaling
# all pixel intensities to the range [0, 1]
data = np.array(data, dtype="float") / 255.0

# encode the labels (which are currently strings) as integers and then
# one-hot encode them
le = LabelEncoder()
labels = le.fit_transform(labels)
labels = np_utils.to_categorical(labels, 2)

# partition the data into training and testing splits using 75% of
# the data for training and the remaining 25% for testing
(trainX, testX, trainY, testY) = train_test_split(data, labels,
                                                  test_size=0.25, random_state=42)
trainY = to_categorical(trainY, 2)
testY = to_categorical(testY, 2)

# construct the training image generator for data augmentation
aug = ImageDataGenerator(rotation_range=20, zoom_range=0.15, brightness_range=[0.5, 1.5],
                         width_shift_range=0.2, height_shift_range=0.2,
                         shear_range=0.15, horizontal_flip=True, fill_mode="nearest")

# initialize the optimizer and model
print("[INFO] compiling model...")
input = Input(shape=(height, width, depth))
labellabel = Input(shape=(classes,))
# if we are using "channels first", update the input shape and channels dimension
chanDim = -1
if K.image_data_format() == "channels_first":
    inputShape = (depth, height, width)
    chanDim = 1

x = Conv2D(32, kernel_size=(3, 3), padding="same", activation="relu")(input)
x = BatchNormalization(axis=chanDim)(x)
x = Conv2D(32, kernel_size=(3, 3), padding="same", activation="relu")(x)
x = BatchNormalization(axis=chanDim)(x)
x = MaxPooling2D(pool_size=(2, 2))(x)
x = Dropout(0.25)(x)

x = Conv2D(64, kernel_size=(3, 3), padding="same", activation="relu")(x)
x = BatchNormalization(axis=chanDim)(x)
x = Conv2D(64, kernel_size=(3, 3), padding="same", activation="relu")(x)
x = BatchNormalization(axis=chanDim)(x)
x = MaxPooling2D(pool_size=(2, 2))(x)
x = Dropout(0.3)(x)

x = Flatten()(x)
x = Dense(128, activation="relu")(x)
x = BatchNormalization(axis=chanDim)(x)
x = Dropout(0.4)(x)

output = ArcFace(classes)([x, labellabel])
model = Model([input, labellabel], output)

opt = Adam(lr=INIT_LR, decay=INIT_LR / EPOCHS)
model.compile(loss="binary_crossentropy", optimizer=opt,
              metrics=["accuracy"])

# visual the architecture of AntiNet
plot_model(model, to_file=r"models\\20190425\\AntiNet.png", show_layer_names=True, show_shapes=True)
print(model.summary())

# train the network
print("[INFO] training network for {} epochs...".format(EPOCHS))
H = model.fit_generator(aug.flow([trainX, trainY], trainY, batch_size=BS),
                        validation_data=([testX, testY], testY), steps_per_epoch=len(trainX) // BS,
                        epochs=EPOCHS)

# evaluate the network
print("[INFO] evaluating network...")
predictions = model.predict([testX, testY], batch_size=BS)
print(classification_report(testY.argmax(axis=1),
                            predictions.argmax(axis=1), target_names=le.classes_))

# save the network to disk
print("[INFO] serializing network to '{}'...".format(args["model"]))
model.save(args["model"])

# save the label encoder to disk
f = open(args["le"], "wb")
f.write(pickle.dumps(le))
f.close()

# plot the training loss and accuracy
plt.style.use("ggplot")
plt.figure()
plt.plot(np.arange(0, EPOCHS), H.history["loss"], label="train_loss")
plt.plot(np.arange(0, EPOCHS), H.history["val_loss"], label="val_loss")
plt.plot(np.arange(0, EPOCHS), H.history["acc"], label="train_acc")
plt.plot(np.arange(0, EPOCHS), H.history["val_acc"], label="val_acc")
plt.title("Training Loss and Accuracy on Dataset")
plt.xlabel("Epoch #")
plt.ylabel("Loss/Accuracy")
plt.legend(loc="lower left")
plt.savefig(args["plot"])
```
i just want to add the designed loss (arcface) instead of previous loss, and i debug it for three days but no progress I make. 

thank you once again if you can deal with it smoothly! @4uiiurz1

**Comment by 4uiiurz1** [comment]
ImageDataGenerator doesn't support the tuple ([X_train, y_train], y_train)...
Please try following code:
```python
class MyImageDataGenerator:
    def __init__(self):
        self.datagen = ImageDataGenerator(rotation_range=20, zoom_range=0.15, brightness_range=[0.5, 1.5],
                         width_shift_range=0.2, height_shift_range=0.2,
                         shear_range=0.15, horizontal_flip=True, fill_mode="nearest")

    def flow(self, x, y=None, batch_size=32, shuffle=True, sample_weight=None,
             seed=None, save_to_dir=None, save_prefix='', save_format='png', subset=None):
        batches = self.datagen.flow(x, y, batch_size, shuffle, sample_weight,
                               seed, save_to_dir, save_prefix, save_format, subset)

        while True:
            x_batch, y_batch = next(batches)

            yield [x_batch, y_batch], y_batch

aug = MyImageDataGenerator()


H = model.fit_generator(aug.flow(trainX, trainY, batch_size=BS),
                        validation_data=([testX, testY], testY), steps_per_epoch=len(trainX) // BS,
                        epochs=EPOCHS)
```

**Comment by GewelsJI** [comment]
@4uiiurz1 I have modified follow your idea, but I got this new issue:
```python
[INFO] training network for 50 epochs...
Traceback (most recent call last):
  File "train_modified.py", line 163, in <module>
    epochs=EPOCHS)
  File "C:\Users\Gepeng-Ji\Anaconda3\envs\keras\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Gepeng-Ji\Anaconda3\envs\keras\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\Gepeng-Ji\Anaconda3\envs\keras\lib\site-packages\keras\engine\training_generator.py", line 144, in fit_generator
    val_x, val_y, val_sample_weight)
  File "C:\Users\Gepeng-Ji\Anaconda3\envs\keras\lib\site-packages\keras\engine\training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "C:\Users\Gepeng-Ji\Anaconda3\envs\keras\lib\site-packages\keras\engine\training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_2 to have 2 dimensions, but got array with shape (78, 2, 2)

```

**Comment by 4uiiurz1** [comment]
It's because that labels are one-hot encoded twice.
Please try to remove following line:
```python
labels = np_utils.to_categorical(labels, 2)
```

**Comment by GewelsJI** [comment]
I am so careless!
thx your help! good luck to you! @4uiiurz1

**Comment by GewelsJI** [comment]
firstly, thank your help last time but today I face another problem when I load the modified training script by Arcface loss function
```python
 File "liveness_demo.py", line 42, in <module>
    model = load_model(args["model"])
  File "D:\Software_01\Anaconda\lib\site-packages\keras\engine\saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "D:\Software_01\Anaconda\lib\site-packages\keras\engine\saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "D:\Software_01\Anaconda\lib\site-packages\keras\engine\saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "D:\Software_01\Anaconda\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "D:\Software_01\Anaconda\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "D:\Software_01\Anaconda\lib\site-packages\keras\engine\network.py", line 1022, in from_config
    process_layer(layer_data)
  File "D:\Software_01\Anaconda\lib\site-packages\keras\engine\network.py", line 1008, in process_layer
    custom_objects=custom_objects)
  File "D:\Software_01\Anaconda\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "D:\Software_01\Anaconda\lib\site-packages\keras\utils\generic_utils.py", line 138, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown layer: ArcFace

```
@4uiiurz1 what should I do for it?

**Comment by 4uiiurz1** [comment]
You can load the model like following:
```python
model = load_model(args["model"], custom_objects={'ArcFace': ArcFace})
```

**Comment by GewelsJI** [comment]
I'm so sorry to disturb you so many times, this is my entire code
```python
# import the necessary packages
from imutils.video import VideoStream
from keras.preprocessing.image import img_to_array
from keras.models import load_model
from arcface.metrics import ArcFace
import numpy as np
import argparse
import imutils
import pickle
import time
import cv2
import os

# construct the argument parse and parse the arguments
ap = argparse.ArgumentParser()
ap.add_argument("-m", "--model", type=str, required=True,
	help="path to trained model")
ap.add_argument("-l", "--le", type=str, required=True,
	help="path to label encoder")
ap.add_argument("-d", "--detector", type=str, required=True,
	help="path to OpenCV's deep learning face detector")
ap.add_argument("-c", "--confidence", type=float, default=0.7,
	help="minimum probability to filter weak detections")
args = vars(ap.parse_args())

# load our serialized face detector from disk
print("[INFO] loading face detector...")
protoPath = os.path.sep.join([args["detector"], "deploy.prototxt"])
modelPath = os.path.sep.join([args["detector"],
	"res10_300x300_ssd_iter_140000.caffemodel"])
net = cv2.dnn.readNetFromCaffe(protoPath, modelPath)

# load the liveness detector model and label encoder from disk
print("[INFO] loading liveness detector...")
# model = load_model(args["model"])
model = load_model(args["model"], custom_objects={"ArcFace": ArcFace})
print("[INFO] model loading successfully")
le = pickle.loads(open(args["le"], "rb").read())

# initialize the video stream and allow the camera sensor to warmup
print("[INFO] starting video stream...")
vs = VideoStream(src=0).start()
time.sleep(2.0)

# loop over the frames from the video stream
while True:
	# grab the frame from the threaded video stream and resize it
	# to have a maximum width of 600 pixels
	frame = vs.read()
	frame = imutils.resize(frame, width=600)

	# grab the frame dimensions and convert it to a blob
	(h, w) = frame.shape[:2]
	blob = cv2.dnn.blobFromImage(cv2.resize(frame, (300, 300)), 1.0,
		(300, 300), (104.0, 177.0, 123.0))

	# pass the blob through the network and obtain the detections and predictions
	net.setInput(blob)
	detections = net.forward()
	print("detections {} {} {}".format(type(detections), detections.shape, detections))
	# loop over the detections
	for i in range(0, detections.shape[2]):
		# extract the confidence (i.e., probability) associated with the
		# prediction
		confidence = detections[0, 0, i, 2]

		# filter out weak detections
		if confidence > args["confidence"]:
			# compute the (x, y)-coordinates of the bounding box for
			# the face and extract the face ROI
			box = detections[0, 0, i, 3:7] * np.array([w, h, w, h])
			print("box{},{}".format(type(box), box.shape))
			(startX, startY, endX, endY) = box.astype("int")

			# ensure the detected bounding box does fall outside the
			# dimensions of the frame
			startX = max(0, startX)
			startY = max(0, startY)
			endX = min(w, endX)
			endY = min(h, endY)

			# extract the face ROI and then preproces it in the exact
			# same manner as our training data
			face = frame[startY:endY, startX:endX]
			face = cv2.resize(face, (32, 32))
			face = face.astype("float") / 255.0
			face = img_to_array(face)
			face = np.expand_dims(face, axis=0)

			# pass the face ROI through the trained liveness detector
			# model to determine if the face is "real" or "fake"
			preds = model.predict(face)[0]
			j = np.argmax(preds)
			LE = le.classes_[j]

			# draw the label and bounding box on the frame
			label = "{}: {:.4f}".format(LE, preds[j])
			# print(LE, label, LE == "real")
			if LE == "real":
				r, g, b = 0, 255, 0
			else:
				r, g, b = 0, 0, 255

			cv2.putText(frame, label, (startX, startY - 10),
				cv2.FONT_HERSHEY_SIMPLEX, 0.5, (r, g, b), 2)
			cv2.rectangle(frame, (startX, startY), (endX, endY),
				(r, g, b), 2)


	# show the output frame and wait for a key press
	cv2.imshow("Face Anti-spoofing System [WHU-NERCMS]", frame)
	key = cv2.waitKey(1) & 0xFF

	# if the `q` key was pressed, break from the loop
	if key == ord("q"):
		break

# do a bit of cleanup
cv2.destroyAllWindows()
vs.stop()
```
BUT, when I run it after modification that following your suggestions(`model = load_model(args["model"], custom_objects={'ArcFace': ArcFace})`), i get this error:

```python
Traceback (most recent call last):
  File "D:\Software_01\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 1659, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 10 and 2 for 'arc_face_1/mul' (op: 'Mul') with input shapes: [?,10
], [?,2].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "liveness_demo.py", line 46, in <module>
    model = load_model(args["model"], custom_objects={"ArcFace": ArcFace})
  File "D:\Software_01\Anaconda\lib\site-packages\keras\engine\saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "D:\Software_01\Anaconda\lib\site-packages\keras\engine\saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "D:\Software_01\Anaconda\lib\site-packages\keras\engine\saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "D:\Software_01\Anaconda\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "D:\Software_01\Anaconda\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "D:\Software_01\Anaconda\lib\site-packages\keras\engine\network.py", line 1032, in from_config
    process_node(layer, node_data)
  File "D:\Software_01\Anaconda\lib\site-packages\keras\engine\network.py", line 991, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "D:\Software_01\Anaconda\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "F:\0_Research\0_MyPaper_LivenessDetection\CodeLib\Liveness Detection (Adrian Rosebrock)\liveness-detection-opencv(test)\arcface\metrics.py", line 42, in c
all
    logits = logits * (1 - y) + target_logits * y
  File "D:\Software_01\Anaconda\lib\site-packages\tensorflow\python\ops\math_ops.py", line 812, in binary_op_wrapper
    return func(x, y, name=name)
  File "D:\Software_01\Anaconda\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1078, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "D:\Software_01\Anaconda\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 6175, in mul
    "Mul", x=x, y=y, name=name)
  File "D:\Software_01\Anaconda\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "D:\Software_01\Anaconda\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "D:\Software_01\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "D:\Software_01\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 1823, in __init__
    control_input_ops)
  File "D:\Software_01\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 10 and 2 for 'arc_face_1/mul' (op: 'Mul') with input shapes: [?,10], [?,2].
```
So I modify it by this [link](https://stackoverflow.com/questions/42407628/valueerror-dimensions-must-be-equal-but-are-784-and-500-for-mul-op-mul) 

this code block in the 43 lines of `metrics.py files` 
```python
        # original 
        #logits = logits * (1 - y) + target_logits * y
        # after modified
        logits = tf.add(tf.matmul(logits, (1-y)), tf.matmul(target_logits, y))
```
and another error occurred:
```python
Traceback (most recent call last):
  File "D:\Software_01\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 1659, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 1 in both shapes must be equal, but are 10 and 2. Shapes are [256,10] and [256,2]. for 'As
sign_30' (op: 'Assign') with input shapes: [256,10], [256,2].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "liveness_demo.py", line 46, in <module>
    model = load_model(args["model"], custom_objects={"ArcFace": ArcFace})
  File "D:\Software_01\Anaconda\lib\site-packages\keras\engine\saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "D:\Software_01\Anaconda\lib\site-packages\keras\engine\saving.py", line 287, in _deserialize_model
    K.batch_set_value(weight_value_tuples)
  File "D:\Software_01\Anaconda\lib\site-packages\keras\backend\tensorflow_backend.py", line 2465, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "D:\Software_01\Anaconda\lib\site-packages\tensorflow\python\ops\variables.py", line 1762, in assign
    name=name)
  File "D:\Software_01\Anaconda\lib\site-packages\tensorflow\python\ops\state_ops.py", line 223, in assign
    validate_shape=validate_shape)
  File "D:\Software_01\Anaconda\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 67, in assign
    use_locking=use_locking, name=name)
  File "D:\Software_01\Anaconda\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "D:\Software_01\Anaconda\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "D:\Software_01\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "D:\Software_01\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 1823, in __init__
    control_input_ops)
  File "D:\Software_01\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 1 in both shapes must be equal, but are 10 and 2. Shapes are [256,10] and [256,2]. for 'Assign_30' (op: 'Assign') with input shapes: [256,10
], [256,2].
```
what should I do  something for it? thx! 😭 @4uiiurz1

**Comment by 4uiiurz1** [comment]
Please try the following code:
```python
x = Conv2D(32, kernel_size=(3, 3), padding="same", activation="relu")(input)
x = BatchNormalization(axis=chanDim)(x)
x = Conv2D(32, kernel_size=(3, 3), padding="same", activation="relu")(x)
x = BatchNormalization(axis=chanDim)(x)
x = MaxPooling2D(pool_size=(2, 2))(x)
x = Dropout(0.25)(x)

x = Conv2D(64, kernel_size=(3, 3), padding="same", activation="relu")(x)
x = BatchNormalization(axis=chanDim)(x)
x = Conv2D(64, kernel_size=(3, 3), padding="same", activation="relu")(x)
x = BatchNormalization(axis=chanDim)(x)
x = MaxPooling2D(pool_size=(2, 2))(x)
x = Dropout(0.3)(x)

x = Flatten()(x)
x = Dense(128, activation="relu")(x)
x = BatchNormalization(axis=chanDim)(x)
x = Dropout(0.4)(x)

output = ArcFace(classes)([x, label])
model = Model([input, label], output)

model.load_weights(args["model"])
```

**Comment by GewelsJI** [comment]
I must mention that this python script is a new one called `"liveness_demo.py"` used for detecting face and judging the genuine/fake face, instead of the previous training script. Therefore, I think we need not add the model architecture before we load it.

**Comment by 4uiiurz1** [comment]
If the model contains the original layer, you need to pass the original layer class as custom_objects to **load_model**.
However, an error occurs because you can't specify the value of the num_classes of the ArcFace layer.
So, there are two solutions.
1. Use **load_weights**:
```python
x = Conv2D(32, kernel_size=(3, 3), padding="same", activation="relu")(input)
x = BatchNormalization(axis=chanDim)(x)
x = Conv2D(32, kernel_size=(3, 3), padding="same", activation="relu")(x)
x = BatchNormalization(axis=chanDim)(x)
x = MaxPooling2D(pool_size=(2, 2))(x)
x = Dropout(0.25)(x)

x = Conv2D(64, kernel_size=(3, 3), padding="same", activation="relu")(x)
x = BatchNormalization(axis=chanDim)(x)
x = Conv2D(64, kernel_size=(3, 3), padding="same", activation="relu")(x)
x = BatchNormalization(axis=chanDim)(x)
x = MaxPooling2D(pool_size=(2, 2))(x)
x = Dropout(0.3)(x)

x = Flatten()(x)
x = Dense(128, activation="relu")(x)
x = BatchNormalization(axis=chanDim)(x)
x = Dropout(0.4)(x)

output = ArcFace(classes)([x, labellabel])
model = Model([input, labellabel], output)

model.load_weights(args["model"])
```

2. Change default num_classes of ArcFace and use **load_model**:
```python
class ArcFace(Layer):
    def __init__(self, n_classes=2, s=30.0, m=0.50, regularizer=None, **kwargs):
        super(ArcFace, self).__init__(**kwargs)
        self.n_classes = n_classes
        self.s = s
        self.m = m
        self.regularizer = regularizers.get(regularizer)

    def build(self, input_shape):
        super(ArcFace, self).build(input_shape[0])
        self.W = self.add_weight(name='W',
                                shape=(input_shape[0][-1], self.n_classes),
                                initializer='glorot_uniform',
                                trainable=True,
                                regularizer=self.regularizer)

    def call(self, inputs):
        x, y = inputs
        c = K.shape(x)[-1]
        # normalize feature
        x = tf.nn.l2_normalize(x, axis=1)
        # normalize weights
        W = tf.nn.l2_normalize(self.W, axis=0)
        # dot product
        logits = x @ W
        # add margin
        # clip logits to prevent zero division when backward
        theta = tf.acos(K.clip(logits, -1.0 + K.epsilon(), 1.0 - K.epsilon()))
        target_logits = tf.cos(theta + self.m)
        # sin = tf.sqrt(1 - logits**2)
        # cos_m = tf.cos(logits)
        # sin_m = tf.sin(logits)
        # target_logits = logits * cos_m - sin * sin_m
        #
        logits = logits * (1 - y) + target_logits * y
        # feature re-scale
        logits *= self.s
        out = tf.nn.softmax(logits)

        return out

    def compute_output_shape(self, input_shape):
        return (None, self.n_classes)

model = load_model(args["model"], custom_objects={'ArcFace': ArcFace})
```

**Comment by GewelsJI** [comment]
Thank you again, I will have a try for it!

**Comment by HoaiAn0906** [comment]
> Thank you again, I will have a try for it!

Hello, Can you help me?.
arcface_model = load_model('ArcFace_Model.h5', custom_objects={'ArcFace': ArcFace})
ValueError: Unknown config_item: 'L2'. Please ensure you are using a `keras.utils.custom_object_scope` and that this object is included in the scope. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
